### ISSUE TITLE
[Feature Request] Filter by number of sold products

### ISSUE THREAD

**Issue by victay44** [icetbr/webext-shopee-advanced-search#2]
Hi icetbr,
Thank you so much for this script. Could I request that a feature to filter for only items with a minimum number of sold times? For example, only show items that have been sold at least 10 times. Example attached. 
![image](https://user-images.githubusercontent.com/99031336/206954211-400578cf-c0eb-434c-b2c5-a166d2c9c856.png)

**Comment by icetbr** [comment]
Good idea! My stopped working and I just restored it. I'm behind a lot of work. I will try to do this soon enough.

**Comment by icetbr** [comment]
Done, let me know if it doesn't work. If products with over 1000 "solds" are a problem, send me a screenshot of the item. In my language they are set as "1,2mil vendidos".

**Comment by victay44** [comment]
Doesn't seem to work on shopee.vn. @icetbr 
Could you double check it?

**Comment by icetbr** [comment]
Fixed in 1.1.1. If anybody wants a fix for their country, send me a screenshot or something so I can know the number format Shopee uses:

/home/ddv/dev/projects/webext-shopee-advanced-search/src/content.js:16
```js
    assert.equal(parseNumber('Đã bán 13,7k'), 13700);
    assert.equal(parseNumber('5,2mil vendidos'), 5200);
    assert.equal(parseNumber('20 sold'), 20);
    assert.equal(parseNumber(''), NaN);
    assert.equal(parseNumber(null), NaN);
```

**Comment by victay44** [comment]
hi @icetbr Can I request a feature to filter by maximum number of sold items as well? Shopee is now filled with artificial/ inflated sale counts so I'd think it's a good idea to also filter out the fake ones by limiting.

**Comment by icetbr** [comment]
I added to OpenUserJS the new version, still waiting for approval on Chrome and FF. I'll let you know when it goes up.

**Comment by victay44** [comment]
Thanks for the quick work. But I think the latest ver (1.4 ?) broke on shopee.vn, I no longer see the search bar :(
Could you help take another look?

**Comment by icetbr** [comment]
You got it from OpenUserJS right? It's a bit hard to test on that domain (.vn) as I get a 1s view before auto redirect. But i could see the bar on Firefox.

On Chrome is complicated. Are you using tampermonkey?

https://www.tampermonkey.net/faq.php#Q209

The extension is still waiting for approval on both chrome and firefox :-(

**Comment by victay44** [comment]
I'm on MS edge (chromium) and ViolentMonkey. I have tried tampermonkey (official and beta) on Edge as well but neither worked.

**Comment by icetbr** [comment]
I'm off windows, I'll try some other time. But It's chrome based, and should have the same problems. Do you have other scripts on ViolentMonkey? Do they work?

If just this one, that faq session I mentioned still applies

**Comment by victay44** [comment]
I only enabled your script in Tampermonkey so no interractions between scripts. I did try a random script in Tampermonkey and that worked. Thanks for your work.

**Comment by icetbr** [comment]
Please delete these lines in the top of the script.

```js
global.document = global.document || {};
```

I assume this doesn't show for you. If so, TamperMonkey is installed correctly.
![Image](https://github.com/user-attachments/assets/ba9fbffc-2d31-4341-a582-6e5c25242ed8)

This should work. I was lazy and did not test on Chrome, on FF those lines re ignored.

Let me know if it works.

**Comment by victay44** [comment]
It works now, following your instructions. Thanks
