### ISSUE TITLE
Both userscript and extension stopped working as of Nov 16. 23

### ISSUE THREAD

**Issue by victay44** [icetbr/webext-shopee-advanced-search#3]
Hi icetbr,

The script completely stopped working as of today. As can be seen in this screenshot below. Could you help take a look? 
I have tried Chrominum Edge, Firefox and Chrome but all produced the same issue. 

![image](https://github.com/icetbr/webext-shopee-advanced-search/assets/99031336/cfda6d8c-01bc-4100-81ef-8455141bf872)

**Comment by icetbr** [comment]
I will take a look, thanks for reporting.

**Comment by icetbr** [comment]
I fixed it, it will take some time to show up on the addons store. You can use the version from userscripts if in a hurry.

**Comment by icetbr** [comment]
FF fixed version is on!

**Comment by icetbr** [comment]
Chrome is also on. Let me know it you have any problem.
