### ISSUE TITLE
it worked for a while, but stopped working

### ISSUE THREAD

**Issue by bosskeito** [icetbr/webext-shopee-advanced-search#5]
i used it last week and it went very well, it filtered everything after the whole page had loaded

unfortunately, the extension stopped working after a week when i need to browse the site again
i'm using DuckDuckGo Privacy Essentials while i browsed around the internet, which blocks trackers. the console log is full of blocked trackers but the extension still doesnt work even if i disable DDG-PE

the extension runs but doesn't filter anything at all. please see attached txt file with 1st and 2nd pages of what i see during my search

[console logs.txt](https://github.com/icetbr/webext-shopee-advanced-search/files/14844607/console.logs.txt)
![Screenshot 2024-04-03 at 07-22-23 cotton shorts - Best Prices and Online Promos - Apr 2024 Shopee Philippines](https://github.com/icetbr/webext-shopee-advanced-search/assets/24731983/7cf3f068-7dd2-4f95-84ff-aa0df977c7c2)
![Screenshot 2024-04-03 at 07-22-01 cotton shorts - Best Prices and Online Promos - Apr 2024 Shopee Philippines](https://github.com/icetbr/webext-shopee-advanced-search/assets/24731983/5c419ca0-1659-41be-a1cd-f21fea9e4ec5)

**Comment by icetbr** [comment]
I will take a look

**Comment by icetbr** [comment]
Fixed it, but I'm off my work PC, maybe tomorrow I will upload it. Then it will take a few days to chrome/firefox to approve it.

If you want to use tampermonkey, here is the fixed version meanwhile.

https://gist.github.com/icetbr/c42378cc8ecb244abe1980ab04ffcab4

**Comment by bosskeito** [comment]
can confirm it is now working, thanks for the quick fix

**Comment by icetbr** [comment]
Thanks for reporting!
